### ISSUE TITLE
Release 1.0.1 does not match up with the commit specified

### ISSUE THREAD

**Issue by arueth** [QualiSystems/Ixia-Chassis-Shell#3]
The release tagged 1.0.1 does not seem to match up with the commit specified.

**Comment by shmir** [comment]
Release in both master and development branches is 1.0.3 now.
Preview release will be updated after I get OK for the offline requirements.

**Comment by shmir** [comment]
Oops... not all versions in the driver are aligned...

**Comment by arueth** [comment]
Also, the source code used to build the 1.0.1 release package was not the same as the source listed on the release page. Can you fix this or take down the package. Right now the current 1.0.1 release creates Port Groups instead of Ports.

**Comment by shmir** [comment]
In 1.0.7-Preview all numbers are aligned.
