### ISSUE TITLE
Ixia-Chassis-Shell 1.2.0-PREVIEW release is not working

### ISSUE THREAD

**Issue by arueth** [QualiSystems/Ixia-Chassis-Shell#9]
The ixia_chassis_shell.zip for the Ixia-Chassis-Shell 1.2.0-PREVIEW release contains a bad driver that has:

    def initialize(self, context):
        """
        :type context: cloudshell.shell.core.driver_context.InitCommandContext
        """

        self.logger = tg_helper.get_logger()
        self.handler.initialize(context, self.logger)

It is missing the context parameter in the get_logger() call.

**Comment by arueth** [comment]
The driver also contains the .idea directory and .pyc files.

**Comment by Costya-Y** [comment]
Hi @shmir ,

I think we can close this issue since there are a lot of packages that were released later, with a fix. 
Also, we might need to hide Ixia-Chassis-Shell 1.2.0-PREVIEW release.

What do you think?

Thank you,
Costya

**Comment by Costya-Y** [comment]
Ixia-Chassis-Shell 1.2.0-PREVIEW release removed
